"""
hfa-core/src/hfa/core/config.py
IRONCLAD — Central settings class (Pydantic BaseSettings).

All environment variables are read through this class.
Direct os.environ.get() calls anywhere in the codebase are forbidden.

Usage
-----
  from hfa.core.config import settings

  api_key = settings.OPENAI_API_KEY
  redis_url = settings.REDIS_URL

Environment variables can be provided via:
  * Shell environment
  * .env file (loaded by python-dotenv if pydantic-settings detects it)
  * Docker / Kubernetes secret mounts
  * HashiCorp Vault agent sidecar (writes to .env or shell env)
"""
from __future__ import annotations

import logging
from typing import Optional

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)


class Settings(BaseSettings):
    """
    Application-wide configuration loaded from environment variables.

    All fields have sane defaults where possible.
    Required fields (no default) will raise at startup if not set.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=True,
        extra="ignore",          # tolerate unknown env-vars silently
    )

    # ------------------------------------------------------------------
    # Application
    # ------------------------------------------------------------------
    APP_ENV: str = Field(
        default="development",
        description="Runtime environment: development | staging | production",
    )
    LOG_LEVEL: str = Field(
        default="INFO",
        description="Python logging level: DEBUG | INFO | WARNING | ERROR | CRITICAL",
    )
    SERVICE_NAME: str = Field(
        default="hfa-tools",
        description="Service name used in structured log output and tracing.",
    )

    # ------------------------------------------------------------------
    # LLM Provider
    # ------------------------------------------------------------------
    OPENAI_API_KEY: str = Field(
        ...,
        description="OpenAI API key. Required. Never hard-coded.",
    )
    LLM_PROVIDER: str = Field(
        default="openai",
        description="LLM provider identifier: openai | anthropic | azure",
    )
    LLM_MODEL: str = Field(
        default="gpt-4o-2024-08-06",
        description="Default model name passed to the LLM provider.",
    )
    LLM_MAX_RETRIES: int = Field(
        default=3,
        ge=0,
        le=10,
        description="Max retry attempts for failed LLM calls.",
    )
    LLM_TIMEOUT_SECONDS: int = Field(
        default=30,
        ge=1,
        le=300,
        description="Per-call timeout for LLM requests.",
    )

    # ------------------------------------------------------------------
    # Redis
    # ------------------------------------------------------------------
    REDIS_URL: str = Field(
        default="redis://localhost:6379/0",
        description="Redis connection URL. Format: redis://[user:pass@]host:port/db",
    )
    REDIS_MAX_CONNECTIONS: int = Field(
        default=20,
        ge=1,
        le=500,
        description="Maximum connections in the Redis connection pool.",
    )
    REDIS_SOCKET_TIMEOUT: float = Field(
        default=5.0,
        ge=0.1,
        le=60.0,
        description="Socket timeout in seconds for Redis operations.",
    )

    # ------------------------------------------------------------------
    # Budget
    # ------------------------------------------------------------------
    DEFAULT_BUDGET_LIMIT_USD: float = Field(
        default=10.0,
        gt=0,
        le=100_000.0,
        description="Default per-run budget limit in USD when no policy overrides.",
    )
    BUDGET_ALERT_FRACTION: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="Emit warning when spent/limit exceeds this fraction.",
    )

    # ------------------------------------------------------------------
    # SignedLedger / Ed25519 keys
    # ------------------------------------------------------------------
    HFA_LEDGER_KEY_ID: Optional[str] = Field(
        default=None,
        description="Logical key identifier. Set by genesis.py generate-ledger-key.",
    )
    HFA_LEDGER_PRIVATE_KEY_B64: Optional[str] = Field(
        default=None,
        description=(
            "Base64-encoded PKCS8 PEM of the Ed25519 private key. "
            "Generated by: python scripts/genesis.py generate-ledger-key --env-snippet"
        ),
    )
    HFA_LEDGER_PUBLIC_KEY_B64: Optional[str] = Field(
        default=None,
        description="Base64-encoded SubjectPublicKeyInfo PEM of the Ed25519 public key.",
    )

    # ------------------------------------------------------------------
    # Docker / Sandbox (Sprint 3)
    # ------------------------------------------------------------------
    DOCKER_BASE_IMAGE: str = Field(
        default="python:3.12-slim",
        description="Base Docker image used by the sandbox pool.",
    )
    SANDBOX_POOL_SIZE: int = Field(
        default=4,
        ge=1,
        le=32,
        description="Number of pre-warmed sandbox containers to maintain.",
    )
    SANDBOX_EXEC_TIMEOUT_SECONDS: int = Field(
        default=30,
        ge=1,
        le=300,
        description="Max execution time for code inside a sandbox container.",
    )
    SANDBOX_TMPFS_SIZE_MB: int = Field(
        default=64,
        ge=16,
        le=512,
        description="tmpfs size in MiB for sandbox /tmp mount.",
    )

    # ------------------------------------------------------------------
    # Tracing / Observability (Sprint 5)
    # ------------------------------------------------------------------
    JAEGER_AGENT_HOST: str = Field(
        default="localhost",
        description="Jaeger agent host for OpenTelemetry trace export.",
    )
    JAEGER_AGENT_PORT: int = Field(
        default=6831,
        ge=1,
        le=65535,
        description="Jaeger agent UDP port.",
    )
    OTEL_SERVICE_NAME: Optional[str] = Field(
        default=None,
        description="OpenTelemetry service name. Defaults to SERVICE_NAME if not set.",
    )

    # ------------------------------------------------------------------
    # Validators
    # ------------------------------------------------------------------

    @field_validator("APP_ENV")
    @classmethod
    def validate_app_env(cls, v: str) -> str:
        allowed = {"development", "staging", "production", "test"}
        if v not in allowed:
            raise ValueError(f"APP_ENV must be one of {allowed}, got {v!r}")
        return v

    @field_validator("LOG_LEVEL")
    @classmethod
    def validate_log_level(cls, v: str) -> str:
        allowed = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}
        v_upper = v.upper()
        if v_upper not in allowed:
            raise ValueError(f"LOG_LEVEL must be one of {allowed}, got {v!r}")
        return v_upper

    @field_validator("LLM_PROVIDER")
    @classmethod
    def validate_llm_provider(cls, v: str) -> str:
        allowed = {"openai", "anthropic", "azure"}
        if v not in allowed:
            raise ValueError(f"LLM_PROVIDER must be one of {allowed}, got {v!r}")
        return v

    # ------------------------------------------------------------------
    # Computed helpers
    # ------------------------------------------------------------------

    @property
    def is_production(self) -> bool:
        return self.APP_ENV == "production"

    @property
    def otel_service(self) -> str:
        return self.OTEL_SERVICE_NAME or self.SERVICE_NAME


# ---------------------------------------------------------------------------
# Singleton — imported everywhere as `from hfa.core.config import settings`
# ---------------------------------------------------------------------------

settings = Settings()

logger.debug(
    "Settings loaded: env=%s provider=%s model=%s",
    settings.APP_ENV,
    settings.LLM_PROVIDER,
    settings.LLM_MODEL,
)
