
# V23.6A Reason Codes (DAG aligned)

TASK_COMMITTED = "TASK_COMMITTED"
TASK_ALREADY_TERMINAL = "TASK_ALREADY_TERMINAL"
TASK_STATE_CONFLICT = "TASK_STATE_CONFLICT"
TASK_ILLEGAL_TRANSITION = "TASK_ILLEGAL_TRANSITION"
TASK_BLOCKED_BY_FAILURE = "TASK_BLOCKED_BY_FAILURE"
