
TASK_COMMITTED = "TASK_COMMITTED"
TASK_ALREADY_TERMINAL = "TASK_ALREADY_TERMINAL"
TASK_STATE_CONFLICT = "TASK_STATE_CONFLICT"
TASK_ILLEGAL_TRANSITION = "TASK_ILLEGAL_TRANSITION"
TASK_BLOCKED_BY_FAILURE = "TASK_BLOCKED_BY_FAILURE"

TASK_HEARTBEAT_RECORDED = "TASK_HEARTBEAT_RECORDED"
TASK_HEARTBEAT_OWNER_MISMATCH = "TASK_HEARTBEAT_OWNER_MISMATCH"
TASK_STALE_DETECTED = "TASK_STALE_DETECTED"
TASK_REQUEUED = "TASK_REQUEUED"
TASK_ALREADY_REQUEUED = "TASK_ALREADY_REQUEUED"
TASK_TERMINAL = "TASK_TERMINAL"
TASK_RETRY_EXHAUSTED = "TASK_RETRY_EXHAUSTED"

TASK_OWNERSHIP_FENCED = "TASK_OWNERSHIP_FENCED"
TASK_FRESH_HEARTBEAT = "TASK_FRESH_HEARTBEAT"

TASK_CLAIMED = "task_claimed"
TASK_ALREADY_OWNED = "task_already_owned"
TASK_RUNNING_STATE_CONFLICT = "task_running_state_conflict"
TASK_MISSING_IN_REDIS = "task_missing_in_redis"

TASK_OWNER_MISMATCH = "task_owner_mismatch"


class TaskReason:
    CLAIMED = TASK_CLAIMED
    ALREADY_OWNED = TASK_ALREADY_OWNED
    RUNNING_STATE_CONFLICT = TASK_RUNNING_STATE_CONFLICT
    MISSING_IN_REDIS = TASK_MISSING_IN_REDIS
    OWNER_MISMATCH = TASK_OWNER_MISMATCH

    HEARTBEAT_RECORDED = TASK_HEARTBEAT_RECORDED
    HEARTBEAT_OWNER_MISMATCH = TASK_HEARTBEAT_OWNER_MISMATCH
    STALE_DETECTED = TASK_STALE_DETECTED
    REQUEUED = TASK_REQUEUED
    ALREADY_REQUEUED = TASK_ALREADY_REQUEUED
    TERMINAL = TASK_TERMINAL
    RETRY_EXHAUSTED = TASK_RETRY_EXHAUSTED
    OWNERSHIP_FENCED = TASK_OWNERSHIP_FENCED
    FRESH_HEARTBEAT = TASK_FRESH_HEARTBEAT
